version: '3.5'
services:
  pc-builder-app:
    container_name: pc-builder-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - DOMAIN=/pc-builder-app
      - ENV=PROD
    env_file:
      - .env


  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    user: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pc_builder_db
    volumes:
      - postgres-pc-builder:/var/lib/postgresql/data


  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 9090:8080
    restart: unless-stopped
volumes:
  postgres-pc-builder: