version: '3.5'
services:
  pc-builder-app:
    container_name: pc-builder-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      # - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - DOMAIN=/pc-builder-app
      - ENV=PROD
    env_file:
      - .env
    command: sh -c "chmod +x ./entrypoint.sh && ./entrypoint.sh"


  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    user: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pc_builder_db
    volumes:
      - postgres-pc-builder:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html/


  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 9090:8080
    restart: unless-stopped
volumes:
  postgres-pc-builder: